<?php
$title = 'My albums';
$this->headTitle($title);
?>
<link rel="stylesheet" type="text/css" href="<?php // echo $this->basePath('css/bootstrap.min.css');  ?>"/>
<link rel="stylesheet" type="text/css" href="css/dataTables.bootstrap.min.css"/>
<div class="container">          
    <div id="page-wrapper" >
        <div class="container-fluid">
            <!-- Page Heading -->
            <div class="row well" id="main" style="height: 130px;" >
                <div class="col-sm-12 col-md-12 " id="content">
                    <h1><?= $this->escapeHtml($title) ?></h1> 
                </div>
                <p class="pull-right">
                    <a class="btn btn-sm btn-danger" href="<?= $this->url('album', ['action' => 'add']) ?>">Add new album</a>
                </p>
            </div>
            <!-- /.row -->

        </div>
    </div>  
    <div class="panel panel-default " id="panel">
        <div class="panel-body">        

            <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Artist</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>


                    <?php foreach ($albums as $album) : ?>
                        <tr>
                            <td><?= $this->escapeHtml($album->title) ?></td>
                            <td><?= $this->escapeHtml($album->artist) ?></td>
                            <td>
                                <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>">Edit</a>
                                <a href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>">Delete</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <tbody>
            </table>

        </div>
    </div>

</div>

<script type="text/javascript" src="<?php echo $this->basePath('js/jquery-1.12.4.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('js/jquery.dataTables.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('js/dataTables.bootstrap.min.js'); ?>"></script>

<script>
    $(document).ready(function () {
        $('#example').DataTable();
    });</script>
