

<style>
    #panel{
        height: 300px;
        border: 2px solid #a6e1ec;
    }
</style>


<div class="container">
    <div>  <h1>acceuil</h1>

    </div>


    <div class="well">


        <div class="row" style="margin-top: 80px">
            <div class="col-md-6 " >
                <div class="panel panel-default " id="panel">
                    <div class="panel-body">
                        <p>

                        </p>


                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="panel panel-default" id="panel">

                    <div class="panel-body">
                        <p>

                        </p>


                    </div>
                </div>
            </div>


        </div>

        <div class="row" >
            <div class="col-md-6">
                <div class="panel panel-default" id="panel">

                    <div class="panel-body">
                        <p>

                        </p>


                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="panel panel-default" id="panel">

                    <div class="panel-body">
                        <p>

                        </p>


                    </div>
                </div>
            </div>


        </div>

        <div class="row" >
            <div class="col-md-6">
                <div class="panel panel-default" id="panel">

                    <div class="panel-body">
                        <p>

                        </p>


                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="panel panel-default" id="panel">

                    <div class="panel-body">
                        <p>

                        </p>


                    </div>
                </div>
            </div>


        </div>
    </div>
</div>

